version: 1.0.0.{build}

platform: x64

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\midstar\plm

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get github.com\mattn\goveralls
  - go get github.com\midstar\proci
  - go get github.com\kardianos\service
 
build_script:
  - go test -v -cover github.com\midstar\plm -coverprofile=coverage.out
  - '%GOPATH%/bin/goveralls -coverprofile=coverage.out -service=appveyor-ci -repotoken=%COVERALLS_TOKEN%'
  - '%GOPATH%\src\github.com\midstar\plm\scripts\install_plm.bat %APPVEYOR_BUILD_VERSION%'
  - '%GOPATH%\src\github.com\midstar\plm\scripts\install_plmc.bat %APPVEYOR_BUILD_VERSION%'
  - 'makensis -DVERSION=%APPVEYOR_BUILD_VERSION% %GOPATH%\src\github.com\midstar\plm\scripts\plm_windows_installer.nsi'